### PR TITLE
Fix simple_form gem integration.

### LINKED ISSUE #248: Support for Simple Form 3.1.0
Ran into this issue:
```
undefined method `has_attribute?' for #<ArbitraryObject:0x007ff8b35adc10>
```

`ArbitraryObject` is the class inheriting from `ActiveInteraction::Base`

Using `ActiveInteraction` version 1.4.1

### PR DESCRIPTION
**Pull request by AaronLasseigne**
fixes #248

### CODE REVIEW

**Comment by AaronLasseigne** [comment]
@tfausak review please

**Comment by AaronLasseigne** [comment]
:cactus:

File: lib/active_interaction/concerns/active_recordable.rb [hunk 1]
```diff
@@ -29,5 +29,32 @@ def column_for_attribute(name)
...
+    #
+    #   Interaction.new.has_attribute?(:not_a_filter)
+    #   # => false
+    #
+    # @return [Boolean]
+    #
+    # @since 1.5.0
+    #
+    # rubocop:disable PredicateName
+    def has_attribute?(name)
```
Comment (tfausak) [inline lib/active_interaction/concerns/active_recordable.rb]: This can go all on one line.

``` rb
def has_attribute?(name) # rubocop:disable PredicateName
```

**Comment by tfausak** [comment]
:shipit:

File: lib/active_interaction/concerns/active_recordable.rb (hunk 1 above)
Comment (AaronLasseigne) [inline lib/active_interaction/concerns/active_recordable.rb]: Good to know.
